### ISSUE TITLE
Invision Prototype Access

### ISSUE THREAD

**Issue by jsonin** [all-of-us/workbench#4274]
Going through https://github.com/all-of-us/workbench/blob/master/ui/docs/style-guide.md to bone up on the most recent designs...

https://projects.invisionapp.com/d/main#/projects/prototypes/12820961

... is this an open 'prototype' (ie no credentials)?

**Comment by calbach** [comment]
Thanks for noting this. I'm checking whether this setting is intentional.

**Comment by calbach** [comment]
Sorry, I misread your question. No - it is not an open prototype. Note that the README you are referencing is a coding style guide, intended for developers.

If you have a legitimate need to access this, you can send your request through support@researchallofus.org
