### ISSUE TITLE
Missing `await` in `puppeteer-custom-environment.ts`

### ISSUE THREAD

**Issue by brady-ds** [all-of-us/workbench#5301]
On [this line of code](https://github.com/all-of-us/workbench/blob/c63d8590c2362576277fd06344490ba3eedf1060/e2e/puppeteer-custom-environment.ts#L65):

```js
super.handleTestEvent(event, state);
```

an `async` method is being called without the expected `await`, so the call does nothing (compare other calls to superclass methods in the same class).

See [here](https://github.com/facebook/jest/issues/6527#issuecomment-886111793) for where the bug was originally caught; it has already been fixed in that comment thread.

**Comment by jmthibault79** [comment]
Thanks!
